//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Phoenix3D.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Phoenix3D.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon ConsoleIcon {
            get {
                object obj = ResourceManager.GetObject("ConsoleIcon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name;h;b;tw;tf;r;A;S;Iy;Wyel;Wypl;iy;Avz;Iz;Wzel;Wzpl;iz;Ss;It;Iw;BS235;BS355;BS460;CS235;CS355;CS460
        ///HEA 100;0.096;0.1;0.005;0.008;0.012;2.120E-03;5.600E-01;3.492E-06;7.276E-05;8.301E-05;4.060E-03;7.560E-04;1.338E-06;2.676E-05;4.114E-05;2.510E-03;3.506E-02;5.240E-08;2.580E-09;1;1;1;1;1;1
        ///HEA 120;0.114;0.12;0.005;0.008;0.012;2.530E-03;6.800E-01;6.062E-06;1.063E-04;1.195E-04;4.890E-03;8.460E-04;2.309E-06;3.848E-05;5.885E-05;3.020E-03;3.506E-02;5.990E-08;6.470E-09;1;1;1;1;1;1
        ///HEA 140;0.133;0.14;0.0055;0.00 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string HEASections {
            get {
                return ResourceManager.GetString("HEASections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name;h;b;tw;tf;r;A;S;Iy;Wyel;Wypl;iy;Avz;Iz;Wzel;Wzpl;iz;Ss;It;Iw;BS235;BS355;BS460;CS235;CS355;CS460
        ///IPE 80;0.08;0.046;0.0038;0.0052;0.005;0.00076;0.33;0.000000801;0.00002;0.0000232;0.00324;0.000358;8.49E-08;0.00000369;0.0000058;0.00105;0.0201;0.000000007;1.2E-10;1;1;0;1;1;0
        ///IPE 100;0.1;0.055;0.0041;0.0057;0.007;0.00103;0.4;0.00000171;0.0000342;0.0000394;0.00407;0.000508;0.000000159;0.00000579;0.0000092;0.00124;0.0237;0.000000012;3.5E-10;1;1;0;1;1;0
        ///IPE 120;0.12;0.064;0.0044;0.0063;0.007;0.00132;0.48;0. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string IPESections {
            get {
                return ResourceManager.GetString("IPESections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name;h;b;tw;tf;r;A;S;Iy;Wyel;Wypl;iy;Avz;Iz;Wzel;Wzpl;iz;Ss;It;Iw;BS235;BS355;BS460;CS235;CS355;CS460
        ///IPE 80;0.08;0.046;0.0038;0.0052;0.005;0.00076;0.33;0.000000801;0.00002;0.0000232;0.00324;0.000358;8.49E-08;0.00000369;0.0000058;0.00105;0.0201;0.000000007;1.2E-10;1;1;0;1;1;0
        ///IPE 100;0.1;0.055;0.0041;0.0057;0.007;0.00103;0.4;0.00000171;0.0000342;0.0000394;0.00407;0.000508;0.000000159;0.00000579;0.0000092;0.00124;0.0237;0.000000012;3.5E-10;1;1;0;1;1;0
        ///IPE 120;0.12;0.064;0.0044;0.0063;0.007;0.00132;0.48;0. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string IPNSections {
            get {
                return ResourceManager.GetString("IPNSections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name;h;w;t;A;cy;cz;cu;cv;Iy;Iz;Wy;Wz;Iu;Iv
        ///20x20x3;0.02;0.02;0.003;1.12E-04;6.00E-03;6.00E-03;1.41E-02;8.50E-03;3.90E-09;3.90E-09;2.80E-07;2.80E-07;6.20E-09;1.70E-09
        ///25x25x3;0.025;0.025;0.003;1.42E-04;7.20E-03;7.20E-03;1.77E-02;1.02E-02;8.00E-09;8.00E-09;4.50E-07;4.50E-07;1.27E-08;3.30E-09
        ///25x25x4;0.025;0.025;0.004;1.85E-04;7.60E-03;7.60E-03;1.77E-02;1.08E-02;1.02E-08;1.02E-08;5.90E-07;5.90E-07;1.61E-08;4.30E-09
        ///25x25x5;0.025;0.025;0.005;2.27E-04;8.00E-03;8.00E-03;1.77E-02;1.13E-02;1.20E-08;1.20E-08;7.1 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string LSections {
            get {
                return ResourceManager.GetString("LSections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name;h;b;t;A;cty;ctz;Iy;Iz;iy;iz;Wy.el;Wz.el;Wy.pl;Wz.pl;It;WT;As
        ///RHS 50x30x3.2;0.05;0.03;0.0032;0.00046;12.6;6.380E+00;1.420E-07;6.200E-08;1.760E-02;1.160E-02;5.680E-06;4.130E-06;7.250E-06;5.000E-06;1.420E-07;6.800E-06;1.520E-01
        ///RHS 50x30x3.6;0.05;0.03;0.0036;0.00051;10.9;5.330E+00;1.540E-07;6.670E-08;1.740E-02;1.140E-02;6.160E-06;4.450E-06;7.940E-06;5.460E-06;1.540E-07;7.310E-06;1.510E-01
        ///RHS 50x30x4;0.05;0.03;0.004;0.000559;9.5;4.500E+00;1.650E-07;7.080E-08;1.720E-02;1.130E-02;6.600E-06;4.720E-06;8.59 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RHSections {
            get {
                return ResourceManager.GetString("RHSections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name;h;b;t;A;ct;I;i;Wel;Wpl;It;WT;As
        ///SHS 40x3.2;0.04;0.04;0.0032;0.00046;9.5;1.020E-07;1.490E-02;5.110E-06;6.280E-06;1.650E-07;7.420E-06;1.520E-01
        ///SHS 40x3.6;0.04;0.04;0.0036;0.00051;8.11;1.110E-07;1.470E-02;5.540E-06;6.880E-06;1.810E-07;8.010E-06;1.510E-01
        ///SHS 40x4;0.04;0.04;0.004;0.000559;7;1.180E-07;1.450E-02;5.910E-06;7.440E-06;1.950E-07;8.540E-06;1.500E-01
        ///SHS 40x5;0.04;0.04;0.005;0.000673;5;1.340E-07;1.410E-02;6.680E-06;8.660E-06;2.250E-07;9.600E-06;1.470E-01
        ///SHS 40x6.3;0.04;0.04;0.0063;0.000807; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SHSections {
            get {
                return ResourceManager.GetString("SHSections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name;h;b;tw;tf;r;A;S;Iy;Wyel;Wypl;iy;Avz;Iz;Wzel;Wzpl;iz;Ss;It;Iw;BS235;BS355;BS460;CS235;CS355;CS460
        ///IPE 80;0.08;0.046;0.0038;0.0052;0.005;0.00076;0.33;0.000000801;0.00002;0.0000232;0.00324;0.000358;8.49E-08;0.00000369;0.0000058;0.00105;0.0201;0.000000007;1.2E-10;1;1;0;1;1;0
        ///IPE 100;0.1;0.055;0.0041;0.0057;0.007;0.00103;0.4;0.00000171;0.0000342;0.0000394;0.00407;0.000508;0.000000159;0.00000579;0.0000092;0.00124;0.0237;0.000000012;3.5E-10;1;1;0;1;1;0
        ///IPE 120;0.12;0.064;0.0044;0.0063;0.007;0.00132;0.48;0. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UPESections {
            get {
                return ResourceManager.GetString("UPESections", resourceCulture);
            }
        }
    }
}
